const REGISTERDOCTOR="doctor:REGISTERDOCTOR"
const LOGINDOCTOR="doctor:LOGINDOCTOR"
const GET_ALL_DOCTORS="doctor:GET_ALL_DOCTORS"
const GET_DOCTOR_BY_ID="doctor:GET_DOCTOR_BY_ID"
const UPDATE_DOCTOR="doctor:UPDATE_DOCTOR"
const DELETE_DOCTOR="doctor:DELETE_DOCTOR"
const RESET_PASSWORDDOCTOR = "doctor:RESET_PASSWORDDOCTOR";



const REGISTERPATIENT="patient:REGISTERPATIENT"
const LOGINPATIENT="patient:LOGINPATIENT"
const GET_ALL_PATIENTS="patient:GET_ALL_PATIENTS"
const GET_PATIENT_BY_ID="patient:GET_PATIENT_BY_ID"
const UPDATE_PATIENT="patient:UPDATE_PATIENT"
const DELETE_PATIENT="patient:DELETE_PATIENT"
const RESET_PASSWORDPATIENT = "patient:RESET_PASSWORDPATIENT";





const REGISTERNURSE="nurse:REGISTERNURSE"
const LOGINNURSE="nurse:LOGINNURSE"
const GET_ALL_NURSES="nurse:GET_ALL_NURSES"
const GET_NURSE_BY_ID="nurse:GET_NURSE_BY_ID"
const UPDATE_NURSE="nurse:UPDATE_NURSE"
const DELETE_NURSE="nurse:DELETE_NURSE"
const RESET_PASSWORDNURSE = "nurse:RESET_PASSWORDNURSE";





const REGISTEREMPLOYEE="employee:REGISTEREMPLOYEE"
const LOGINEMPLOYEE="employee:LOGINEMPLOYEE"
const GET_ALL_EMPLOYEES="employee:GET_ALL_EMPLOYEES"
const GET_EMPLOYEE_BY_ID="employee:GET_EMPLOYEE_BY_ID"
const UPDATE_EMPLOYEE="employee:UPDATE_EMPLOYEE"
const DELETE_EMPLOYEE="employee:DELETE_EMPLOYEE"
const RESET_PASSWORDEMPLOYEE = "employee:RESET_PASSWORDEMPLOYEE";



const CREATE_APPOINTMENT="appointment:CREATE_APPOINTMENT"
const GET_ALL_APPOINTMENTS="appointment:GET_ALL_APPOINTMENTS"
const GET_APPOINTMENT_BY_ID="appointment:GET_APPOINTMENT_BY_ID"
const UPDATE_APPOINTMENT="appointment:UPDATE_APPOINTMENT"
const DELETE_APPOINTMENT="appointment:DELETE_APPOINTMENT"




const CREATE_DEPARTMENT="department:CREATE_DEPARTMENT"
const GET_ALL_DEPARTMENTS="department:GET_ALL_DEPARTMENTS"
const GET_DEPARTMENT_BY_ID="department:GET_DEPARTMENT_BY_ID"
const DELETE_DEPARTMENT="department:DELETE_DEPARTMENT"



const CREATE_HOSPITAL="hospital:CREATE_HOSPITAL"
const GET_ALL_HOSPITALS="hospital:GET_ALL_HOSPITALS"
const GET_HOSPITAL_BY_ID="hospital:GET_HOSPITAL_BY_ID"
const UPDATE_HOSPITAL="hospital:UPDATE_HOSPITAL"
const DELETE_HOSPITAL="hospital:DELETE_HOSPITAL"


const CREATE_PAYMENT="payment:CREATE_PAYMENT"



const CREATE_RECORD="record:CREATE_RECORD"
const GET_ALL_RECORDS="record:GET_ALL_RECORDS"
const GET_RECORD_BY_ID="record:GET_RECORD_BY_ID"
const UPDATE_RECORD="record:UPDATE_RECORD"
const DELETE_RECORD="record:DELETE_RECORD"


const CREATE_ROOM="room:CREATE_ROOM"
const GET_ALL_ROOMS="room:GET_ALL_ROOMS"
const GET_ROOM_BY_ID="room:GET_ROOM_BY_ID"
const UPDATE_ROOM="room:UPDATE_ROOM"
const DELETE_ROOM="room:DELETE_ROOM"



module.exports={
    REGISTERDOCTOR,
    LOGINDOCTOR,
    GET_ALL_DOCTORS,
    GET_DOCTOR_BY_ID,
    UPDATE_DOCTOR,
    DELETE_DOCTOR,
    RESET_PASSWORDDOCTOR,


    REGISTERPATIENT,
    LOGINPATIENT,
    GET_ALL_PATIENTS,
    GET_PATIENT_BY_ID,
    UPDATE_PATIENT,
    DELETE_PATIENT,
    RESET_PASSWORDPATIENT,


    REGISTERNURSE,
    LOGINNURSE,
    GET_ALL_NURSES,
    GET_NURSE_BY_ID,
    UPDATE_NURSE,
    DELETE_NURSE,
    RESET_PASSWORDNURSE,


    REGISTEREMPLOYEE,
    LOGINEMPLOYEE,
    GET_ALL_EMPLOYEES,
    GET_EMPLOYEE_BY_ID,
    UPDATE_EMPLOYEE,
    DELETE_EMPLOYEE,
    RESET_PASSWORDEMPLOYEE,


    CREATE_APPOINTMENT,
    GET_ALL_APPOINTMENTS,
    GET_APPOINTMENT_BY_ID,
    UPDATE_APPOINTMENT,
    DELETE_APPOINTMENT,


    CREATE_DEPARTMENT,
    GET_ALL_DEPARTMENTS,
    GET_DEPARTMENT_BY_ID,
    DELETE_DEPARTMENT,

    CREATE_HOSPITAL,
    GET_ALL_HOSPITALS,
    GET_HOSPITAL_BY_ID,
    UPDATE_HOSPITAL,
    DELETE_HOSPITAL,

    CREATE_PAYMENT,


    CREATE_RECORD,
    GET_ALL_RECORDS,
    GET_RECORD_BY_ID,
    UPDATE_RECORD,
    DELETE_RECORD,


    CREATE_ROOM,
    GET_ALL_ROOMS,
    GET_ROOM_BY_ID,
    UPDATE_ROOM,
    DELETE_ROOM

}